dataset: oscar-corpus/OSCAR-2109
configs:
  - deduplicated_gl
columns:
  - text
num_proc: 10
embedder:
  name: SuffixArrayEmbedder
  k: 50
  skip_existing: true
  cache_dir: outputs
  temp_file_prefix: sa
tokenization:
  ngram_size: 12
  level: sentencepiece
cache_dir: .cache
